"""Navigation route manifest for Beacon UX surfaces."""

from core.navigation.areas import (
    DEFAULT_PLUGIN_IDS,
    HIDDEN_BY_DEFAULT_PLUGIN_IDS,
    INTERMEDIATE_PLUGIN_IDS,
    NavigationArea,
    all_areas,
    area_for_plugin,
    default_areas,
    get_area,
    is_plugin_visible_for_level,
    plugin_ids_for_level,
    sidebar_areas_for_level,
    validate_areas,
)
from core.navigation.manifest import (
    NavigationRoute,
    all_routes,
    get_route,
    resolve,
    routes_for_palette,
    routes_for_quick_actions,
    validate_routes,
)
from core.navigation.destinations import (
    ADVANCED_DESTINATION,
    STANDARD_DESTINATIONS,
    all_destinations,
    destinations_for_mode,
    get_destination,
    placement_for_route,
    validate_destinations,
)
from core.navigation.migrations import (
    canonical_persisted_route,
    legacy_experience_for_mode,
    migrate_last_route,
    migrate_quick_action,
    migrate_quick_actions,
    migrate_route_references,
    navigation_mode_from_value,
)
from core.navigation.models import (
    Destination,
    DirectLinkBehavior,
    FedoraVariant,
    NavigationContext,
    NavigationDecision,
    NavigationMode,
    NavigationPolicyResult,
    RoutePlacement,
)
from core.navigation.policy import NavigationPolicy, validate_navigation_policy
from core.navigation.search import (
    GlobalSearchModel,
    SearchFilter,
    SearchResult,
    SearchResultKind,
)

__all__ = [
    "DEFAULT_PLUGIN_IDS",
    "ADVANCED_DESTINATION",
    "STANDARD_DESTINATIONS",
    "Destination",
    "DirectLinkBehavior",
    "FedoraVariant",
    "HIDDEN_BY_DEFAULT_PLUGIN_IDS",
    "INTERMEDIATE_PLUGIN_IDS",
    "NavigationArea",
    "NavigationContext",
    "NavigationDecision",
    "NavigationMode",
    "NavigationPolicy",
    "NavigationPolicyResult",
    "NavigationRoute",
    "GlobalSearchModel",
    "SearchFilter",
    "SearchResult",
    "SearchResultKind",
    "RoutePlacement",
    "all_areas",
    "all_destinations",
    "all_routes",
    "area_for_plugin",
    "default_areas",
    "destinations_for_mode",
    "canonical_persisted_route",
    "get_area",
    "get_destination",
    "get_route",
    "is_plugin_visible_for_level",
    "legacy_experience_for_mode",
    "migrate_last_route",
    "migrate_quick_action",
    "migrate_quick_actions",
    "migrate_route_references",
    "navigation_mode_from_value",
    "placement_for_route",
    "plugin_ids_for_level",
    "resolve",
    "routes_for_palette",
    "routes_for_quick_actions",
    "sidebar_areas_for_level",
    "validate_areas",
    "validate_destinations",
    "validate_navigation_policy",
    "validate_routes",
]
