# flake8: noqa
"""Specialist Tools catalog records for advanced workspace."""

from __future__ import annotations

from typing import Any, Final

RECORDS: Final[dict[str, Any]] = {'plugins': ({'id': 'agents',
              'name': 'Agents',
              'description': 'Manage autonomous system agents for automated monitoring and maintenance.',
              'icon': 'developer-tools',
              'destination_id': 'advanced',
              'module': 'ui.agents_tab',
              'class_name': 'AgentsTab',
              'component': 'specialist',
              'visibility': 'advanced',
              'compat': {},
              'category': 'Maintenance',
              'badge': '',
              'order': 40},
             {'id': 'mesh',
              'name': 'Loofi Link',
              'description': 'Mesh network device discovery, clipboard sync, and file transfer between peers.',
              'icon': 'network-connectivity',
              'destination_id': 'advanced',
              'module': 'ui.mesh_tab',
              'class_name': 'MeshTab',
              'component': 'specialist',
              'visibility': 'advanced',
              'compat': {},
              'category': 'Network',
              'badge': 'advanced',
              'order': 20},
             {'id': 'ai_lab',
              'name': 'AI Lab',
              'description': 'AI model management, voice transcription, and knowledge base indexing.',
              'icon': 'cpu-performance',
              'destination_id': 'advanced',
              'module': 'ui.ai_enhanced_tab',
              'class_name': 'AIEnhancedTab',
              'component': 'specialist',
              'visibility': 'advanced',
              'compat': {},
              'category': 'Tools',
              'badge': 'advanced',
              'order': 30},
             {'id': 'community',
              'name': 'Local Profiles',
              'description': 'Save local profiles, keep a private backup, and inspect quarantined legacy extensions.',
              'icon': 'settings',
              'destination_id': 'advanced',
              'module': 'ui.community_tab',
              'class_name': 'CommunityTab',
              'component': 'specialist',
              'visibility': 'advanced',
              'compat': {},
              'category': 'System',
              'badge': '',
              'order': 40}),
 'routes': ({'id': 'community',
             'label': 'Local Profiles',
             'plugin_id': 'community',
             'category': 'System',
             'icon': 'settings',
             'description': 'Local profiles, private backup, and legacy extension inventory.',
             'aliases': ('Community',),
             'keywords': ('presets', 'profiles', 'backup'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': ''},
            {'id': 'community:presets',
             'label': 'Local Profiles',
             'plugin_id': 'community',
             'category': 'System',
             'icon': 'settings',
             'description': 'Local configuration profiles and private backup.',
             'aliases': ('Presets', 'preset', 'profile'),
             'keywords': ('preset', 'configuration', 'backup'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'presets'},
            {'id': 'community:marketplace',
             'label': 'Marketplace retired',
             'plugin_id': 'community',
             'category': 'System',
             'icon': 'settings',
             'description': 'Compatibility route explaining the retired public Marketplace.',
             'aliases': ('Marketplace',),
             'keywords': ('marketplace', 'retired'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'marketplace'},
            {'id': 'community:plugins',
             'label': 'External plugins retired',
             'plugin_id': 'community',
             'category': 'System',
             'icon': 'settings',
             'description': 'Compatibility route for quarantined legacy extension files.',
             'aliases': ('Plugins',),
             'keywords': ('plugin', 'legacy', 'retired'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'plugins'},
            {'id': 'community:featured',
             'label': 'Featured retired',
             'plugin_id': 'community',
             'category': 'System',
             'icon': 'settings',
             'description': 'Compatibility route explaining the retired public catalog.',
             'aliases': ('Featured',),
             'keywords': ('featured', 'retired'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'featured'},
            {'id': 'agents',
             'label': 'Agents',
             'plugin_id': 'agents',
             'category': 'Maintenance',
             'icon': 'developer-tools',
             'description': 'Automation agents and activity.',
             'aliases': ('Agents',),
             'keywords': ('agent', 'automation'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': ''},
            {'id': 'agents:dashboard',
             'label': 'Agents Dashboard',
             'plugin_id': 'agents',
             'category': 'Maintenance',
             'icon': 'overview-dashboard',
             'description': 'Agent summary and status.',
             'aliases': ('Agent Dashboard',),
             'keywords': ('agent', 'dashboard'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': 'dashboard'},
            {'id': 'agents:my-agents',
             'label': 'My Agents',
             'plugin_id': 'agents',
             'category': 'Maintenance',
             'icon': 'developer-tools',
             'description': 'Configured local agents.',
             'aliases': ('My Agents',),
             'keywords': ('agent', 'list'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': 'my-agents'},
            {'id': 'agents:create',
             'label': 'Create Agent',
             'plugin_id': 'agents',
             'category': 'Maintenance',
             'icon': 'install',
             'description': 'Create a new local automation agent.',
             'aliases': ('Create Agent',),
             'keywords': ('agent', 'create'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': 'create'},
            {'id': 'agents:activity',
             'label': 'Activity Log',
             'plugin_id': 'agents',
             'category': 'Maintenance',
             'icon': 'logs',
             'description': 'Agent execution activity log.',
             'aliases': ('Activity Log',),
             'keywords': ('agent', 'log', 'activity'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': 'activity'},
            {'id': 'mesh',
             'label': 'Loofi Link',
             'plugin_id': 'mesh',
             'category': 'Network',
             'icon': 'network-connectivity',
             'description': 'Device mesh, shared clipboard, and file drop.',
             'aliases': ('Loofi Link', 'Mesh'),
             'keywords': ('mesh', 'devices', 'clipboard', 'file drop'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': ''},
            {'id': 'loofi-link:devices',
             'label': 'Devices',
             'plugin_id': 'mesh',
             'category': 'Network',
             'icon': 'network-connectivity',
             'description': 'Nearby mesh devices.',
             'aliases': ('mesh:devices', 'Devices'),
             'keywords': ('mesh', 'device'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': 'devices'},
            {'id': 'loofi-link:clipboard',
             'label': 'Clipboard',
             'plugin_id': 'mesh',
             'category': 'Network',
             'icon': 'terminal-console',
             'description': 'Shared clipboard between trusted devices.',
             'aliases': ('mesh:clipboard', 'Clipboard'),
             'keywords': ('clipboard', 'copy', 'paste'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': 'clipboard'},
            {'id': 'loofi-link:file-drop',
             'label': 'File Drop',
             'plugin_id': 'mesh',
             'category': 'Network',
             'icon': 'install',
             'description': 'Local file drop between trusted devices.',
             'aliases': ('mesh:file-drop', 'File Drop'),
             'keywords': ('file', 'drop', 'transfer'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': 'file-drop'},
            {'id': 'ai_lab',
             'label': 'AI Lab',
             'plugin_id': 'ai_lab',
             'category': 'Tools',
             'icon': 'cpu-performance',
             'description': 'Local AI models, voice, and knowledge tools.',
             'aliases': ('AI Lab', 'Ollama', 'AI Models', 'Chat'),
             'keywords': ('ai', 'llm', 'ollama', 'models'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': ''},
            {'id': 'ai-lab:models',
             'label': 'Models',
             'plugin_id': 'ai_lab',
             'category': 'Tools',
             'icon': 'cpu-performance',
             'description': 'Local AI model inventory and recommendations.',
             'aliases': ('ai_lab:models', 'Models', 'Ollama', 'AI Models'),
             'keywords': ('models', 'llm', 'ollama'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': 'models'},
            {'id': 'ai-lab:voice',
             'label': 'Voice',
             'plugin_id': 'ai_lab',
             'category': 'Tools',
             'icon': 'terminal-console',
             'description': 'Voice and transcription tools.',
             'aliases': ('ai_lab:voice', 'Voice'),
             'keywords': ('voice', 'transcribe', 'audio'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': 'voice'},
            {'id': 'ai-lab:knowledge',
             'label': 'Knowledge',
             'plugin_id': 'ai_lab',
             'category': 'Tools',
             'icon': 'logs',
             'description': 'Local knowledge and context tooling.',
             'aliases': ('ai_lab:knowledge', 'Knowledge'),
             'keywords': ('knowledge', 'rag', 'documents'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': 'knowledge'}),
 'placements': ({'route_id': 'community',
                 'destination_id': 'advanced',
                 'section_id': 'community',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'community:presets',
                 'destination_id': 'advanced',
                 'section_id': 'community',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'community:marketplace',
                 'destination_id': 'advanced',
                 'section_id': 'community_marketplace',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': 'community:presets',
                 'discoverable': False},
                {'route_id': 'community:plugins',
                 'destination_id': 'advanced',
                 'section_id': 'community_plugins',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': 'community:presets',
                 'discoverable': False},
                {'route_id': 'community:featured',
                 'destination_id': 'advanced',
                 'section_id': 'community_featured',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': 'community:presets',
                 'discoverable': False},
                {'route_id': 'agents',
                 'destination_id': 'advanced',
                 'section_id': 'agents',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'agents:dashboard',
                 'destination_id': 'advanced',
                 'section_id': 'agents',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'agents:my-agents',
                 'destination_id': 'advanced',
                 'section_id': 'agents_list',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'agents:create',
                 'destination_id': 'advanced',
                 'section_id': 'agents_create',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'agents:activity',
                 'destination_id': 'advanced',
                 'section_id': 'agents_activity',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'mesh',
                 'destination_id': 'advanced',
                 'section_id': 'loofi_link',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'loofi-link:devices',
                 'destination_id': 'advanced',
                 'section_id': 'loofi_link',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'loofi-link:clipboard',
                 'destination_id': 'advanced',
                 'section_id': 'loofi_link_clipboard',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'loofi-link:file-drop',
                 'destination_id': 'advanced',
                 'section_id': 'loofi_link_file_drop',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'ai_lab',
                 'destination_id': 'advanced',
                 'section_id': 'ai_lab',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'ai-lab:models',
                 'destination_id': 'advanced',
                 'section_id': 'ai_lab',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'ai-lab:voice',
                 'destination_id': 'advanced',
                 'section_id': 'ai_lab_voice',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'ai-lab:knowledge',
                 'destination_id': 'advanced',
                 'section_id': 'ai_lab_knowledge',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True}),
 'sections': ({'id': 'community',
               'destination_id': 'advanced',
               'label': 'Local Profiles',
               'icon': 'settings',
               'order': 60,
               'default_route_id': 'community',
               'description': 'Local profiles, private backup, and legacy extension inventory.'},
              {'id': 'community_marketplace',
               'destination_id': 'advanced',
               'label': 'Marketplace retired',
               'icon': 'settings',
               'order': 61,
               'default_route_id': 'community:marketplace',
               'description': 'Compatibility route for the retired public catalog.'},
              {'id': 'community_plugins',
               'destination_id': 'advanced',
               'label': 'External plugins retired',
               'icon': 'settings',
               'order': 62,
               'default_route_id': 'community:plugins',
               'description': 'Compatibility route for quarantined legacy files.'},
              {'id': 'community_featured',
               'destination_id': 'advanced',
               'label': 'Featured retired',
               'icon': 'settings',
               'order': 63,
               'default_route_id': 'community:featured',
               'description': 'Compatibility route for the retired public catalog.'},
              {'id': 'loofi_link',
               'destination_id': 'advanced',
               'label': 'Loofi Link',
               'icon': 'network-connectivity',
               'order': 70,
               'default_route_id': 'mesh',
               'description': 'Device sharing and Loofi Link tools.'},
              {'id': 'loofi_link_clipboard',
               'destination_id': 'advanced',
               'label': 'Shared Clipboard',
               'icon': 'network-connectivity',
               'order': 71,
               'default_route_id': 'loofi-link:clipboard',
               'description': 'Share clipboard content with paired devices.'},
              {'id': 'loofi_link_file_drop',
               'destination_id': 'advanced',
               'label': 'File Drop',
               'icon': 'network-connectivity',
               'order': 72,
               'default_route_id': 'loofi-link:file-drop',
               'description': 'Send files to paired devices.'},
              {'id': 'ai_lab',
               'destination_id': 'advanced',
               'label': 'AI Lab',
               'icon': 'developer-tools',
               'order': 80,
               'default_route_id': 'ai_lab',
               'description': 'Local AI models, voice, and knowledge tools.'},
              {'id': 'ai_lab_voice',
               'destination_id': 'advanced',
               'label': 'Voice',
               'icon': 'developer-tools',
               'order': 81,
               'default_route_id': 'ai-lab:voice',
               'description': 'Record and transcribe speech locally.'},
              {'id': 'ai_lab_knowledge',
               'destination_id': 'advanced',
               'label': 'Knowledge',
               'icon': 'developer-tools',
               'order': 82,
               'default_route_id': 'ai-lab:knowledge',
               'description': 'Build and search local knowledge indexes.'},
              {'id': 'agents',
               'destination_id': 'advanced',
               'label': 'Agents',
               'icon': 'developer-tools',
               'order': 90,
               'default_route_id': 'agents',
               'description': 'Local agent management and activity.'},
              {'id': 'agents_list',
               'destination_id': 'advanced',
               'label': 'My Agents',
               'icon': 'developer-tools',
               'order': 91,
               'default_route_id': 'agents:my-agents',
               'description': 'Review and manage configured agents.'},
              {'id': 'agents_create',
               'destination_id': 'advanced',
               'label': 'Create Agent',
               'icon': 'developer-tools',
               'order': 92,
               'default_route_id': 'agents:create',
               'description': 'Create a local agent from a goal.'},
              {'id': 'agents_activity',
               'destination_id': 'advanced',
               'label': 'Agent Activity',
               'icon': 'developer-tools',
               'order': 93,
               'default_route_id': 'agents:activity',
               'description': 'Inspect recent agent activity.'})}
