# flake8: noqa
"""Specialist Tools catalog records for advanced automation."""

from __future__ import annotations

from typing import Any, Final

RECORDS: Final[dict[str, Any]] = {'plugins': ({'id': 'automation',
              'name': 'Automation',
              'description': 'Schedule tasks and replicate system configurations automatically.',
              'icon': 'maintenance-health',
              'destination_id': 'advanced',
              'module': 'ui.automation_tab',
              'class_name': 'AutomationTab',
              'component': 'specialist',
              'visibility': 'advanced',
              'compat': {},
              'category': 'Maintenance',
              'badge': '',
              'order': 50},
             {'id': 'virtualization',
              'name': 'Virtualization',
              'description': 'VM lifecycle management, GPU passthrough setup, and disposable virtual machines.',
              'icon': 'terminal-console',
              'destination_id': 'advanced',
              'module': 'ui.virtualization_tab',
              'class_name': 'VirtualizationTab',
              'component': 'specialist',
              'visibility': 'advanced',
              'compat': {},
              'category': 'Tools',
              'badge': 'advanced',
              'order': 20},
             {'id': 'teleport',
              'name': 'State Teleport',
              'description': 'Capture and restore workspace state including git repos and environment snapshots.',
              'icon': 'network-traffic',
              'destination_id': 'advanced',
              'module': 'ui.teleport_tab',
              'class_name': 'TeleportTab',
              'component': 'specialist',
              'visibility': 'advanced',
              'compat': {},
              'category': 'Maintenance',
              'badge': 'advanced',
              'order': 60}),
 'routes': ({'id': 'automation',
             'label': 'Automation',
             'plugin_id': 'automation',
             'category': 'Maintenance',
             'icon': 'settings',
             'description': 'Scheduler and replicator automation workflows.',
             'aliases': ('Automation', 'Scheduler', 'Replicator'),
             'keywords': ('schedule', 'replicate', 'automation'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': ''},
            {'id': 'automation:scheduler',
             'label': 'Scheduler',
             'plugin_id': 'automation',
             'category': 'Maintenance',
             'icon': 'settings',
             'description': 'Scheduled tasks and systemd timer automation.',
             'aliases': ('Scheduler', 'Cron Jobs'),
             'keywords': ('schedule', 'cron', 'timer'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': 'scheduler'},
            {'id': 'automation:replicator',
             'label': 'Replicator',
             'plugin_id': 'automation',
             'category': 'Maintenance',
             'icon': 'restart',
             'description': 'Export and import system state as repeatable automation.',
             'aliases': ('Replicator', 'Ansible Export'),
             'keywords': ('ansible', 'export', 'import', 'iac'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': 'replicator'},
            {'id': 'teleport',
             'label': 'State Teleport',
             'plugin_id': 'teleport',
             'category': 'Maintenance',
             'icon': 'network-traffic',
             'description': 'Capture, list, and restore workspace state.',
             'aliases': ('State Teleport', 'Teleport'),
             'keywords': ('state', 'teleport', 'capture', 'restore'),
             'risk': 'medium',
             'visibility': 'advanced',
             'subroute': ''},
            {'id': 'virtualization',
             'label': 'Virtualization',
             'plugin_id': 'virtualization',
             'category': 'Packages',
             'icon': 'terminal-console',
             'description': 'Virtual machines, GPU passthrough, and disposable environments.',
             'aliases': ('Virtualization', 'VMs'),
             'keywords': ('vm', 'virt', 'gpu', 'passthrough'),
             'risk': 'medium',
             'visibility': 'advanced',
             'subroute': ''},
            {'id': 'virtualization:vms',
             'label': 'VMs',
             'plugin_id': 'virtualization',
             'category': 'Packages',
             'icon': 'terminal-console',
             'description': 'Virtual machine list and actions.',
             'aliases': ('VMs', 'Virtual Machines'),
             'keywords': ('vm', 'virsh', 'libvirt'),
             'risk': 'medium',
             'visibility': 'advanced',
             'subroute': 'vms'},
            {'id': 'virtualization:gpu-passthrough',
             'label': 'GPU Passthrough',
             'plugin_id': 'virtualization',
             'category': 'Packages',
             'icon': 'hardware-performance',
             'description': 'VFIO GPU passthrough planning.',
             'aliases': ('GPU Passthrough', 'VFIO'),
             'keywords': ('gpu', 'vfio', 'passthrough'),
             'risk': 'high',
             'visibility': 'advanced',
             'subroute': 'gpu-passthrough'},
            {'id': 'virtualization:disposable',
             'label': 'Disposable',
             'plugin_id': 'virtualization',
             'category': 'Packages',
             'icon': 'cleanup',
             'description': 'Disposable virtualization workflows.',
             'aliases': ('Disposable',),
             'keywords': ('temporary', 'sandbox', 'vm'),
             'risk': 'medium',
             'visibility': 'advanced',
             'subroute': 'disposable'}),
 'placements': ({'route_id': 'automation',
                 'destination_id': 'advanced',
                 'section_id': 'automation',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'automation:scheduler',
                 'destination_id': 'advanced',
                 'section_id': 'automation',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'automation:replicator',
                 'destination_id': 'advanced',
                 'section_id': 'automation_replicator',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'teleport',
                 'destination_id': 'advanced',
                 'section_id': 'state_teleport',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'virtualization',
                 'destination_id': 'advanced',
                 'section_id': 'virtualization',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'virtualization:vms',
                 'destination_id': 'advanced',
                 'section_id': 'virtualization',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'virtualization:gpu-passthrough',
                 'destination_id': 'advanced',
                 'section_id': 'virtualization_gpu',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'virtualization:disposable',
                 'destination_id': 'advanced',
                 'section_id': 'virtualization_disposable',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True}),
 'sections': ({'id': 'automation',
               'destination_id': 'advanced',
               'label': 'Automation',
               'icon': 'settings',
               'order': 100,
               'default_route_id': 'automation',
               'description': 'Schedules and automation workflows.'},
              {'id': 'automation_replicator',
               'destination_id': 'advanced',
               'label': 'Replicator',
               'icon': 'settings',
               'order': 101,
               'default_route_id': 'automation:replicator',
               'description': 'Export reproducible system configuration.'},
              {'id': 'state_teleport',
               'destination_id': 'advanced',
               'label': 'State Teleport',
               'icon': 'storage-disk',
               'order': 110,
               'default_route_id': 'teleport',
               'description': 'Move compatible application state.'},
              {'id': 'virtualization',
               'destination_id': 'advanced',
               'label': 'Virtualization',
               'icon': 'hardware-performance',
               'order': 120,
               'default_route_id': 'virtualization',
               'description': 'Virtual machines and disposable environments.'},
              {'id': 'virtualization_gpu',
               'destination_id': 'advanced',
               'label': 'GPU Passthrough',
               'icon': 'hardware-performance',
               'order': 121,
               'default_route_id': 'virtualization:gpu-passthrough',
               'description': 'Review VFIO readiness and setup guidance.'},
              {'id': 'virtualization_disposable',
               'destination_id': 'advanced',
               'label': 'Disposable VMs',
               'icon': 'hardware-performance',
               'order': 122,
               'default_route_id': 'virtualization:disposable',
               'description': 'Create and manage disposable virtual machines.'})}
