# flake8: noqa
"""Specialist Tools catalog records for advanced foundation."""

from __future__ import annotations

from typing import Any, Final

RECORDS: Final[dict[str, Any]] = {'plugins': ({'id': 'performance',
              'name': 'Performance',
              'description': 'Auto-tuner engine for workload detection, kernel tunables, and performance recommendations.',
              'icon': 'cpu-performance',
              'destination_id': 'advanced',
              'module': 'ui.performance_tab',
              'class_name': 'PerformanceTab',
              'component': 'specialist',
              'visibility': 'advanced',
              'compat': {},
              'category': 'Hardware',
              'badge': 'advanced',
              'order': 20},
             {'id': 'development',
              'name': 'Development',
              'description': 'Container management and developer tools including language version managers and VS Code extensions.',
              'icon': 'developer-tools',
              'destination_id': 'advanced',
              'module': 'ui.development_tab',
              'class_name': 'DevelopmentTab',
              'component': 'specialist',
              'visibility': 'advanced',
              'compat': {},
              'category': 'Tools',
              'badge': '',
              'order': 10},
             {'id': 'profiles',
              'name': 'Profiles',
              'description': 'System profile quick-switch for applying and managing configuration profiles.',
              'icon': 'settings',
              'destination_id': 'advanced',
              'module': 'ui.profiles_tab',
              'class_name': 'ProfilesTab',
              'component': 'core',
              'visibility': 'advanced',
              'compat': {},
              'category': 'Appearance',
              'badge': '',
              'order': 30},
             {'id': 'gaming',
              'name': 'Gaming',
              'description': 'Gaming optimization tools including driver setup and performance tweaks.',
              'icon': 'hardware-performance',
              'destination_id': 'advanced',
              'module': 'ui.gaming_tab',
              'class_name': 'GamingTab',
              'component': 'specialist',
              'visibility': 'advanced',
              'compat': {},
              'category': 'Hardware',
              'badge': '',
              'order': 40},
             {'id': 'extensions',
              'name': 'Extensions',
              'description': 'Manage GNOME Shell and KDE Plasma desktop extensions.',
              'icon': 'appearance-theme',
              'destination_id': 'advanced',
              'module': 'ui.extensions_tab',
              'class_name': 'ExtensionsTab',
              'component': 'core',
              'visibility': 'advanced',
              'compat': {},
             'category': 'Appearance',
              'badge': 'new',
              'order': 20},
             {'id': 'logs',
              'name': 'Logs',
              'description': 'Smart log viewer with pattern detection, error summary, and log export.',
              'icon': 'logs',
              'destination_id': 'advanced',
              'module': 'ui.logs_tab',
              'class_name': 'LogsTab',
              'component': 'specialist',
              'visibility': 'advanced',
              'compat': {},
              'category': 'Maintenance',
              'badge': 'advanced',
              'order': 20}),
 'routes': ({'id': 'performance',
             'label': 'Performance',
             'plugin_id': 'performance',
             'category': 'Hardware',
             'icon': 'cpu-performance',
             'description': 'Performance tuning and workload history.',
             'aliases': ('Auto-Tune Performance', 'CPU Governor', 'Show CPU Governor'),
             'keywords': ('governor', 'performance', 'tuning', 'cpu'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': ''},
            {'id': 'gaming',
             'label': 'Gaming',
             'plugin_id': 'gaming',
             'category': 'Hardware',
             'icon': 'cpu-performance',
             'description': 'GameMode, MangoHud, Proton, Wine, and shader cache.',
             'aliases': ('Gaming', 'GameMode', 'MangoHud', 'Proton', 'Wine', 'Shader Cache', 'Steam', 'gaming_mode'),
             'keywords': ('game', 'steam', 'proton', 'mangohud'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},
            {'id': 'profiles',
             'label': 'Profiles',
             'plugin_id': 'profiles',
             'category': 'Appearance',
             'icon': 'settings',
             'description': 'System tuning profiles and active profile state.',
             'aliases': ('Profiles',),
             'keywords': ('profile', 'preset'),
             'risk': 'medium',
             'visibility': 'all',
             'subroute': ''},
            {'id': 'extensions',
             'label': 'Extensions',
             'plugin_id': 'extensions',
             'category': 'Appearance',
             'icon': 'developer-tools',
             'description': 'Desktop extensions and compatibility state.',
             'aliases': ('Extensions',),
             'keywords': ('extension', 'plugin'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': ''},
            {'id': 'development',
             'label': 'Development Tools',
             'plugin_id': 'development',
             'category': 'Tools',
             'icon': 'developer-tools',
             'description': 'Containers and developer tool setup.',
             'aliases': ('Development', 'Developer Tools', 'Developer'),
             'keywords': ('developer', 'containers', 'podman', 'code'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},
            {'id': 'development:containers',
             'label': 'Containers',
             'plugin_id': 'development',
             'category': 'Tools',
             'icon': 'developer-tools',
             'description': 'Container and Distrobox tooling.',
             'aliases': ('Containers', 'Distrobox', 'Podman'),
             'keywords': ('podman', 'docker', 'distrobox', 'container'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'containers'},
            {'id': 'development:developer',
             'label': 'Developer Tools',
             'plugin_id': 'development',
             'category': 'Tools',
             'icon': 'terminal-console',
             'description': 'Editors, compilers, Git, and SDK packages.',
             'aliases': ('Developer', 'VS Code'),
             'keywords': ('git', 'gcc', 'make', 'vscode', 'sdk'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'developer-tools'}),
 'placements': ({'route_id': 'performance',
                 'destination_id': 'advanced',
                 'section_id': 'performance_tuning',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'gaming',
                 'destination_id': 'advanced',
                 'section_id': 'gaming',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'profiles',
                 'destination_id': 'advanced',
                 'section_id': 'profiles',
                 'advanced_only': True,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'extensions',
                 'destination_id': 'advanced',
                 'section_id': 'extensions',
                 'advanced_only': True,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'development',
                 'destination_id': 'advanced',
                 'section_id': 'development',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'development:containers',
                 'destination_id': 'advanced',
                 'section_id': 'development',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'development:developer',
                 'destination_id': 'advanced',
                 'section_id': 'developer_tools',
                 'advanced_only': True,
                 'component_id': 'specialist',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True}),
 'sections': ({'id': 'performance_tuning',
               'destination_id': 'advanced',
               'label': 'Performance Tuning',
               'icon': 'cpu-performance',
               'order': 10,
               'default_route_id': 'performance',
               'description': 'Advanced performance tuning.'},
              {'id': 'gaming',
               'destination_id': 'advanced',
               'label': 'Gaming',
               'icon': 'developer-tools',
               'order': 20,
               'default_route_id': 'gaming',
               'description': 'Gaming-focused system tools.'},
              {'id': 'development',
               'destination_id': 'advanced',
               'label': 'Development',
               'icon': 'developer-tools',
               'order': 30,
               'default_route_id': 'development',
               'description': 'Developer environments and containers.'},
              {'id': 'developer_tools',
               'destination_id': 'advanced',
               'label': 'Developer Tools',
               'icon': 'developer-tools',
               'order': 31,
               'default_route_id': 'development:developer',
               'description': 'Language runtimes and editor tooling.'},
              {'id': 'profiles',
               'destination_id': 'advanced',
               'label': 'Profiles',
               'icon': 'settings',
               'order': 40,
               'default_route_id': 'profiles',
               'description': 'Reusable configuration profiles.'},
              {'id': 'extensions',
               'destination_id': 'advanced',
               'label': 'Extensions',
               'icon': 'developer-tools',
               'order': 50,
               'default_route_id': 'extensions',
               'description': 'Optional Loofi extensions.'})}
