# flake8: noqa
"""Compose destination-owned source records into stable global projections."""

from __future__ import annotations

from typing import Any, Final

from .advanced import RECORDS as ADVANCED_RECORDS
from .desktop import RECORDS as DESKTOP_RECORDS
from .home import RECORDS as HOME_RECORDS
from .network_security import RECORDS as NETWORK_SECURITY_RECORDS
from .settings import RECORDS as SETTINGS_RECORDS
from .software_updates import RECORDS as SOFTWARE_UPDATES_RECORDS
from .system import RECORDS as SYSTEM_RECORDS

DESTINATION_RECORDS: Final[dict[str, dict[str, Any]]] = {
    "home": HOME_RECORDS,
    "software_updates": SOFTWARE_UPDATES_RECORDS,
    "system": SYSTEM_RECORDS,
    "network_security": NETWORK_SECURITY_RECORDS,
    "desktop": DESKTOP_RECORDS,
    "settings": SETTINGS_RECORDS,
    "advanced": ADVANCED_RECORDS,
}

PLUGIN_ORDER = ('atlas_dashboard',
 'agents',
 'automation',
 'system_info',
 'monitor',
 'health',
 'logs',
 'hardware',
 'performance',
 'storage',
 'software',
 'maintenance',
 'snapshots',
 'virtualization',
 'development',
 'network',
 'mesh',
 'security',
 'desktop',
 'profiles',
 'gaming',
 'ai_lab',
 'teleport',
 'diagnostics',
 'community',
 'extensions',
 'backup',
 'settings',
 'activity')
ROUTE_ORDER = ('atlas_dashboard',
 'dashboard',
 'system_info',
 'monitor',
 'system-monitor:performance',
 'system-monitor:processes',
 'community',
 'community:presets',
 'community:marketplace',
 'community:plugins',
 'community:featured',
 'agents',
 'agents:dashboard',
 'agents:my-agents',
 'agents:create',
 'agents:activity',
 'software',
 'software:apps',
 'software:repos',
 'software:flatpak',
 'maintenance',
 'maintenance:updates',
 'maintenance:cleanup',
 'maintenance:smart-updates',
 'maintenance:health-timeline',
 'maintenance:upgrade-assistant',
 'maintenance:action-center',
 'maintenance:overlays',
 'snapshots',
 'hardware',
 'performance',
 'storage',
 'gaming',
 'network',
 'network:connections',
 'network:dns',
 'network:privacy',
 'network:monitoring',
 'mesh',
 'loofi-link:devices',
 'loofi-link:clipboard',
 'loofi-link:file-drop',
 'security',
 'security:overview',
 'security:firewall',
 'security:privacy',
 'security:ports',
 'backup',
 'desktop',
 'desktop:director',
 'desktop:theming',
 'desktop:display',
 'profiles',
 'extensions',
 'settings',
 'settings:appearance',
 'settings:behavior',
 'settings:advanced',
 'settings:repair',
 'settings:about',
 'development',
 'development:containers',
 'development:developer',
 'ai_lab',
 'ai-lab:models',
 'ai-lab:voice',
 'ai-lab:knowledge',
 'automation',
 'automation:scheduler',
 'automation:replicator',
 'health',
 'logs',
 'diagnostics',
 'diagnostics:watchtower',
 'diagnostics:boot',
 'teleport',
 'virtualization',
 'virtualization:vms',
 'virtualization:gpu-passthrough',
 'virtualization:disposable',
 'activity')
PLACEMENT_ORDER = ('atlas_dashboard',
 'dashboard',
 'system_info',
 'monitor',
 'system-monitor:performance',
 'system-monitor:processes',
 'community',
 'community:presets',
 'community:marketplace',
 'community:plugins',
 'community:featured',
 'agents',
 'agents:dashboard',
 'agents:my-agents',
 'agents:create',
 'agents:activity',
 'software',
 'software:apps',
 'software:repos',
 'software:flatpak',
 'maintenance',
 'maintenance:updates',
 'maintenance:cleanup',
 'maintenance:smart-updates',
 'maintenance:health-timeline',
 'maintenance:upgrade-assistant',
 'maintenance:action-center',
 'maintenance:overlays',
 'snapshots',
 'hardware',
 'performance',
 'storage',
 'gaming',
 'network',
 'network:connections',
 'network:dns',
 'network:privacy',
 'network:monitoring',
 'mesh',
 'loofi-link:devices',
 'loofi-link:clipboard',
 'loofi-link:file-drop',
 'security',
 'security:overview',
 'security:firewall',
 'security:privacy',
 'security:ports',
 'backup',
 'desktop',
 'desktop:director',
 'desktop:theming',
 'desktop:display',
 'profiles',
 'extensions',
 'settings',
 'settings:appearance',
 'settings:behavior',
 'settings:advanced',
 'settings:repair',
 'settings:about',
 'development',
 'development:containers',
 'development:developer',
 'ai_lab',
 'ai-lab:models',
 'ai-lab:voice',
 'ai-lab:knowledge',
 'automation',
 'automation:scheduler',
 'automation:replicator',
 'health',
 'logs',
 'diagnostics',
 'diagnostics:watchtower',
 'diagnostics:boot',
 'teleport',
 'virtualization',
 'virtualization:vms',
 'virtualization:gpu-passthrough',
 'virtualization:disposable',
 'activity')
SECTION_ORDER = (('home', 'overview'),
 ('software_updates', 'applications'),
 ('software_updates', 'repositories'),
 ('software_updates', 'flatpak'),
 ('software_updates', 'updates'),
 ('software_updates', 'cleanup'),
 ('software_updates', 'fedora_upgrade'),
 ('software_updates', 'maintenance_review'),
 ('software_updates', 'overlays'),
 ('system', 'overview'),
 ('system', 'performance'),
 ('system', 'processes'),
 ('system', 'hardware_power'),
 ('system', 'storage'),
 ('system', 'system_check'),
 ('system', 'troubleshooting'),
 ('system', 'boot_diagnostics'),
 ('system', 'recovery_points'),
 ('network_security', 'connections'),
 ('network_security', 'dns'),
 ('network_security', 'network_privacy'),
 ('network_security', 'network_monitoring'),
 ('network_security', 'security_overview'),
 ('network_security', 'firewall'),
 ('network_security', 'privacy'),
 ('network_security', 'exposure'),
 ('network_security', 'backups'),
 ('desktop', 'appearance'),
 ('desktop', 'windows'),
 ('desktop', 'displays'),
 ('settings', 'appearance'),
 ('settings', 'behavior'),
 ('settings', 'advanced'),
 ('settings', 'repair'),
 ('settings', 'about'),
 ('advanced', 'performance_tuning'),
 ('advanced', 'gaming'),
 ('advanced', 'development'),
 ('advanced', 'developer_tools'),
 ('advanced', 'profiles'),
 ('advanced', 'extensions'),
 ('advanced', 'community'),
 ('advanced', 'community_marketplace'),
 ('advanced', 'community_plugins'),
 ('advanced', 'community_featured'),
 ('advanced', 'loofi_link'),
 ('advanced', 'loofi_link_clipboard'),
 ('advanced', 'loofi_link_file_drop'),
 ('advanced', 'ai_lab'),
 ('advanced', 'ai_lab_voice'),
 ('advanced', 'ai_lab_knowledge'),
 ('advanced', 'agents'),
 ('advanced', 'agents_list'),
 ('advanced', 'agents_create'),
 ('advanced', 'agents_activity'),
 ('advanced', 'automation'),
 ('advanced', 'automation_replicator'),
 ('advanced', 'state_teleport'),
 ('advanced', 'virtualization'),
 ('advanced', 'virtualization_gpu'),
 ('advanced', 'virtualization_disposable'),
 ('system', 'activity_recovery'))
DESTINATION_ORDER = ('home', 'software_updates', 'system', 'network_security', 'desktop', 'settings', 'advanced')



def compose_catalog_data() -> dict[str, tuple[dict[str, Any], ...]]:
    """Compose destination-owned records into the established global order."""
    plugins = {record["id"]: record for records in DESTINATION_RECORDS.values() for record in records["plugins"]}
    routes = {record["id"]: record for records in DESTINATION_RECORDS.values() for record in records["routes"]}
    placements = {
        record["route_id"]: record
        for records in DESTINATION_RECORDS.values()
        for record in records["placements"]
    }
    sections = {
        (record["destination_id"], record["id"]): record
        for records in DESTINATION_RECORDS.values()
        for record in records["sections"]
    }
    destinations = {destination_id: records["destination"] for destination_id, records in DESTINATION_RECORDS.items()}
    return {
        "plugins": tuple(plugins[plugin_id] for plugin_id in PLUGIN_ORDER),
        "routes": tuple(routes[route_id] for route_id in ROUTE_ORDER),
        "placements": tuple(placements[route_id] for route_id in PLACEMENT_ORDER),
        "sections": tuple(sections[section_key] for section_key in SECTION_ORDER),
        "destinations": tuple(destinations[destination_id] for destination_id in DESTINATION_ORDER),
    }
