# flake8: noqa
"""Destination-owned product catalog records for desktop."""

from __future__ import annotations

from typing import Any, Final

RECORDS: Final[dict[str, Any]] = {'plugins': ({'id': 'desktop',
              'name': 'Desktop',
              'description': 'Window manager configuration, tiling setup, theming, and dotfile synchronization.',
              'icon': 'appearance-theme',
              'destination_id': 'desktop',
              'module': 'ui.desktop_tab',
              'class_name': 'DesktopTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'Appearance',
              'badge': '',
              'order': 10},),
 'routes': ({'id': 'desktop',
             'label': 'Desktop',
             'plugin_id': 'desktop',
             'category': 'Appearance',
             'icon': 'appearance-theme',
             'description': 'Window management, theming, and display settings.',
             'aliases': ('Desktop', 'Director', 'Theming'),
             'keywords': ('window', 'theme', 'display'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},
            {'id': 'desktop:director',
             'label': 'Window Manager',
             'plugin_id': 'desktop',
             'category': 'Appearance',
             'icon': 'appearance-theme',
             'description': 'Window manager and tiling preset controls.',
             'aliases': ('Director', 'Window Manager', 'Tiling Presets'),
             'keywords': ('window', 'kwin', 'tiling'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'window-manager'},
            {'id': 'desktop:theming',
             'label': 'Theming',
             'plugin_id': 'desktop',
             'category': 'Appearance',
             'icon': 'appearance-theme',
             'description': 'GTK, Qt, icons, and font theme controls.',
             'aliases': ('Theming', 'Icons', 'Fonts'),
             'keywords': ('theme', 'icons', 'fonts', 'gtk', 'qt'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'theming'},
            {'id': 'desktop:display',
             'label': 'Display',
             'plugin_id': 'desktop',
             'category': 'Appearance',
             'icon': 'overview-dashboard',
             'description': 'Display and monitor preferences.',
             'aliases': ('Display',),
             'keywords': ('display', 'monitor', 'screen'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'display'}),
 'placements': ({'route_id': 'desktop',
                 'destination_id': 'desktop',
                 'section_id': 'appearance',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'desktop:director',
                 'destination_id': 'desktop',
                 'section_id': 'windows',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True,
                 'native_handoff_id': 'plasma.window.management'},
                {'route_id': 'desktop:theming',
                 'destination_id': 'desktop',
                 'section_id': 'appearance',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True,
                 'native_handoff_id': 'plasma.appearance'},
                {'route_id': 'desktop:display',
                 'destination_id': 'desktop',
                 'section_id': 'displays',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True,
                 'native_handoff_id': 'plasma.display'}),
 'sections': ({'id': 'appearance',
               'destination_id': 'desktop',
               'label': 'Appearance',
               'icon': 'appearance-theme',
               'order': 10,
               'default_route_id': 'desktop',
               'description': 'Desktop theme and visual preferences.'},
              {'id': 'windows',
               'destination_id': 'desktop',
               'label': 'Windows',
               'icon': 'appearance-theme',
               'order': 20,
               'default_route_id': 'desktop:director',
               'description': 'Window-management behavior.'},
              {'id': 'displays',
               'destination_id': 'desktop',
               'label': 'Displays',
               'icon': 'hardware-performance',
               'order': 30,
               'default_route_id': 'desktop:display',
               'description': 'Display layout and scaling.'}),
 'destination': {'id': 'desktop',
                 'label': 'Desktop',
                 'icon': 'appearance-theme',
                 'default_route_id': 'desktop',
                 'route_ids': ('desktop', 'desktop:director', 'desktop:theming', 'desktop:display'),
                 'advanced_only': False}}
