# flake8: noqa
"""Destination-owned product catalog records for home."""

from __future__ import annotations

from typing import Any, Final

RECORDS: Final[dict[str, Any]] = {'plugins': ({'id': 'atlas_dashboard',
              'name': 'Home',
              'description': 'System status, the next useful action, and common Fedora tasks.',
              'icon': 'home',
              'destination_id': 'home',
              'module': 'ui.atlas_dashboard_tab',
              'class_name': 'AtlasDashboardTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'System',
              'badge': 'recommended',
              'order': 0},),
 'routes': ({'id': 'atlas_dashboard',
             'label': 'Home',
             'plugin_id': 'atlas_dashboard',
             'category': 'System',
             'icon': 'home',
             'description': 'System status, the next useful action, and common Fedora tasks.',
             'aliases': ('atlas', 'atlas-home', 'fedora-control-center'),
             'keywords': ('home', 'beacon', 'tasks', 'readiness'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},),
 'placements': ({'route_id': 'atlas_dashboard',
                 'destination_id': 'home',
                 'section_id': 'overview',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},),
 'sections': ({'id': 'overview',
               'destination_id': 'home',
               'label': 'Overview',
               'icon': 'home',
               'order': 10,
               'default_route_id': 'atlas_dashboard',
               'description': 'Current state and recommended next steps.'},),
 'destination': {'id': 'home',
                 'label': 'Home',
                 'icon': 'home',
                 'default_route_id': 'atlas_dashboard',
                 'route_ids': ('atlas_dashboard',),
                 'advanced_only': False}}
