# flake8: noqa
"""Destination-owned product catalog records for network_security."""

from __future__ import annotations

from typing import Any, Final

RECORDS: Final[dict[str, Any]] = {'plugins': ({'id': 'network',
              'name': 'Network',
              'description': 'Comprehensive network management including connections, DNS, privacy, and monitoring.',
              'icon': 'network-connectivity',
              'destination_id': 'network_security',
              'module': 'ui.network_tab',
              'class_name': 'NetworkTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'Network',
              'badge': 'recommended',
              'order': 10},
             {'id': 'security',
              'name': 'Security & Privacy',
              'description': 'Security hardening including firewall, USB guard, port auditing, and telemetry removal.',
              'icon': 'security-shield',
              'destination_id': 'network_security',
              'module': 'ui.security_tab',
              'class_name': 'SecurityTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'Security',
              'badge': 'recommended',
              'order': 10},
             {'id': 'backup',
              'name': 'Backup',
              'description': 'Create, manage, and restore system snapshots via Timeshift or Snapper.',
              'icon': 'storage-disk',
              'destination_id': 'network_security',
              'module': 'ui.backup_tab',
              'class_name': 'BackupTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'Security',
              'badge': 'new',
              'order': 20}),
 'routes': ({'id': 'network',
             'label': 'Network',
             'plugin_id': 'network',
             'category': 'Network',
             'icon': 'network-connectivity',
             'description': 'Connections, DNS, privacy, and network monitoring.',
             'aliases': ('Network',),
             'keywords': ('dns', 'privacy', 'connections', 'traffic'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},
            {'id': 'network:connections',
             'label': 'Connections',
             'plugin_id': 'network',
             'category': 'Network',
             'icon': 'network-connectivity',
             'description': 'Network interfaces, Wi-Fi, and VPN connections.',
             'aliases': ('Connections', 'Network Connections'),
             'keywords': ('interface', 'wifi', 'vpn'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'connections'},
            {'id': 'network:dns',
             'label': 'DNS',
             'plugin_id': 'network',
             'category': 'Network',
             'icon': 'network-connectivity',
             'description': 'DNS provider and resolver configuration.',
             'aliases': ('DNS', 'DNS Provider', 'Show DNS Config', 'Flush DNS Cache'),
             'keywords': ('dns', 'nameserver', 'resolver'),
             'risk': 'medium',
             'visibility': 'all',
             'subroute': 'dns'},
            {'id': 'network:privacy',
             'label': 'Network Privacy',
             'plugin_id': 'network',
             'category': 'Network',
             'icon': 'security-shield',
             'description': 'Network privacy and MAC randomization.',
             'aliases': ('Network Privacy', 'MAC Randomization'),
             'keywords': ('mac', 'randomization', 'privacy'),
             'risk': 'medium',
             'visibility': 'all',
             'subroute': 'privacy'},
            {'id': 'network:monitoring',
             'label': 'Monitoring',
             'plugin_id': 'network',
             'category': 'Network',
             'icon': 'network-traffic',
             'description': 'Network traffic and connection monitoring.',
             'aliases': ('Monitoring', 'Network Monitor'),
             'keywords': ('traffic', 'bandwidth', 'connection'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'monitoring'},
            {'id': 'security',
             'label': 'Security & Privacy',
             'plugin_id': 'security',
             'category': 'Security',
             'icon': 'security-shield',
             'description': 'Security posture, ports, firewall, USB, and sandboxing.',
             'aliases': ('Security', 'Security & Privacy'),
             'keywords': ('security', 'privacy', 'firewall', 'ports'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},
            {'id': 'security:overview',
             'label': 'Security Overview',
             'plugin_id': 'security',
             'category': 'Security',
             'icon': 'security-shield',
             'description': 'Security score and hardening overview.',
             'aliases': ('Security Score', 'Run Security Scan'),
             'keywords': ('score', 'audit', 'hardening'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'overview'},
            {'id': 'security:firewall',
             'label': 'Firewall',
             'plugin_id': 'security',
             'category': 'Security',
             'icon': 'security-shield',
             'description': 'Firewall zones and service exposure.',
             'aliases': ('Firewall', 'Toggle Firewall'),
             'keywords': ('firewall', 'firewalld', 'zone'),
             'risk': 'medium',
             'visibility': 'all',
             'subroute': 'firewall'},
            {'id': 'security:privacy',
             'label': 'Privacy',
             'plugin_id': 'security',
             'category': 'Security',
             'icon': 'security-shield',
             'description': 'Telemetry and privacy controls.',
             'aliases': ('Telemetry', 'Security Privacy'),
             'keywords': ('telemetry', 'tracking', 'privacy'),
             'risk': 'medium',
             'visibility': 'all',
             'subroute': 'privacy'},
            {'id': 'security:ports',
             'label': 'Ports',
             'plugin_id': 'security',
             'category': 'Security',
             'icon': 'search',
             'description': 'Open port auditing.',
             'aliases': ('Port Auditor', 'Check Open Ports'),
             'keywords': ('port', 'scan', 'ss'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'ports'},
            {'id': 'backup',
             'label': 'Backups',
             'plugin_id': 'backup',
             'category': 'Security',
             'icon': 'storage-disk',
             'description': 'Guided system backup protection and restore workflows.',
             'aliases': ('Backup', 'System Backup'),
             'keywords': ('backup', 'restore', 'protection'),
             'risk': 'medium',
             'visibility': 'beginner',
             'subroute': ''}),
 'placements': ({'route_id': 'network',
                 'destination_id': 'network_security',
                 'section_id': 'connections',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'network:connections',
                 'destination_id': 'network_security',
                 'section_id': 'connections',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True,
                 'native_handoff_id': 'plasma.network.connections'},
                {'route_id': 'network:dns',
                 'destination_id': 'network_security',
                 'section_id': 'dns',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'network:privacy',
                 'destination_id': 'network_security',
                 'section_id': 'network_privacy',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'network:monitoring',
                 'destination_id': 'network_security',
                 'section_id': 'network_monitoring',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'security',
                 'destination_id': 'network_security',
                 'section_id': 'security_overview',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'security:overview',
                 'destination_id': 'network_security',
                 'section_id': 'security_overview',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'security:firewall',
                 'destination_id': 'network_security',
                 'section_id': 'firewall',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'security:privacy',
                 'destination_id': 'network_security',
                 'section_id': 'privacy',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'security:ports',
                 'destination_id': 'network_security',
                 'section_id': 'exposure',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'backup',
                 'destination_id': 'network_security',
                 'section_id': 'backups',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True}),
 'sections': ({'id': 'connections',
               'destination_id': 'network_security',
               'label': 'Connections',
               'icon': 'network-connectivity',
               'order': 10,
               'default_route_id': 'network',
               'description': 'Network connections and current connectivity.'},
              {'id': 'dns',
               'destination_id': 'network_security',
               'label': 'DNS',
               'icon': 'network-connectivity',
               'order': 20,
               'default_route_id': 'network:dns',
               'description': 'DNS configuration and resolution.'},
              {'id': 'network_privacy',
               'destination_id': 'network_security',
               'label': 'Connection Privacy',
               'icon': 'security-shield',
               'order': 30,
               'default_route_id': 'network:privacy',
               'description': 'Privacy settings for network connections.'},
              {'id': 'network_monitoring',
               'destination_id': 'network_security',
               'label': 'Network Monitoring',
               'icon': 'network-traffic',
               'order': 40,
               'default_route_id': 'network:monitoring',
               'description': 'Inspect current network activity.'},
              {'id': 'security_overview',
               'destination_id': 'network_security',
               'label': 'Security Overview',
               'icon': 'security-shield',
               'order': 50,
               'default_route_id': 'security',
               'description': 'Review the system security posture.'},
              {'id': 'firewall',
               'destination_id': 'network_security',
               'label': 'Firewall',
               'icon': 'security-shield',
               'order': 60,
               'default_route_id': 'security:firewall',
               'description': 'Review and manage firewall state.'},
              {'id': 'privacy',
               'destination_id': 'network_security',
               'label': 'System Privacy',
               'icon': 'security-shield',
               'order': 70,
               'default_route_id': 'security:privacy',
               'description': 'Review system-wide privacy settings.'},
              {'id': 'exposure',
               'destination_id': 'network_security',
               'label': 'Network Exposure',
               'icon': 'network-traffic',
               'order': 80,
               'default_route_id': 'security:ports',
               'description': 'Inspect listening services and open ports.'},
              {'id': 'backups',
               'destination_id': 'network_security',
               'label': 'Backups',
               'icon': 'storage-disk',
               'order': 90,
               'default_route_id': 'backup',
               'description': 'Configure and review data backups.'}),
 'destination': {'id': 'network_security',
                 'label': 'Network & Security',
                 'icon': 'security-shield',
                 'default_route_id': 'network',
                 'route_ids': ('network',
                               'network:connections',
                               'network:dns',
                               'network:privacy',
                               'network:monitoring',
                               'security',
                               'security:overview',
                               'security:firewall',
                               'security:privacy',
                               'security:ports',
                               'backup'),
                 'advanced_only': False}}
