# flake8: noqa
"""Destination-owned product catalog records for settings."""

from __future__ import annotations

from typing import Any, Final

RECORDS: Final[dict[str, Any]] = {'plugins': ({'id': 'settings',
              'name': 'Settings',
              'description': 'Configure appearance, behavior, and advanced application options.',
              'icon': 'settings',
              'destination_id': 'settings',
              'module': 'ui.settings_tab',
              'class_name': 'SettingsTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'Appearance',
              'badge': '',
              'order': 100},),
 'routes': ({'id': 'settings',
             'label': 'Settings',
             'plugin_id': 'settings',
             'category': 'Appearance',
             'icon': 'settings',
             'description': 'Application appearance, behavior, and advanced settings.',
             'aliases': ('Settings',),
             'keywords': ('settings', 'preferences'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},
            {'id': 'settings:appearance',
             'label': 'Appearance',
             'plugin_id': 'settings',
             'category': 'Appearance',
             'icon': 'appearance-theme',
             'description': 'Application appearance preferences.',
             'aliases': ('Settings Appearance',),
             'keywords': ('appearance', 'theme'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'appearance'},
            {'id': 'settings:behavior',
             'label': 'Behavior',
             'plugin_id': 'settings',
             'category': 'Appearance',
             'icon': 'settings',
             'description': 'Application behavior preferences.',
             'aliases': ('Behavior',),
             'keywords': ('behavior', 'preferences'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'behavior'},
            {'id': 'settings:advanced',
             'label': 'Specialist Tools',
             'plugin_id': 'settings',
             'category': 'Appearance',
             'icon': 'settings',
             'description': 'Navigation mode and advanced application preferences.',
             'aliases': ('Advanced',),
             'keywords': ('advanced', 'developer', 'mode'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'advanced'},
            {'id': 'settings:repair',
             'label': 'Repair Loofi',
             'plugin_id': 'settings',
             'category': 'Appearance',
             'icon': 'maintenance-health',
             'description': 'Inspect, back up, and preview restore of Loofi application state.',
             'aliases': ('State Doctor', 'State & Recovery', 'Repair Loofi'),
             'keywords': ('state', 'doctor', 'repair', 'backup', 'restore'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'repair'},
            {'id': 'settings:about',
             'label': 'About',
             'plugin_id': 'settings',
             'category': 'Appearance',
             'icon': 'info',
             'description': 'Version, build, runtime, and Fedora support information.',
             'aliases': ('About Loofi',),
             'keywords': ('version', 'build', 'support', 'runtime'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'about'}),
 'placements': ({'route_id': 'settings',
                 'destination_id': 'settings',
                 'section_id': 'appearance',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'settings:appearance',
                 'destination_id': 'settings',
                 'section_id': 'appearance',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'settings:behavior',
                 'destination_id': 'settings',
                 'section_id': 'behavior',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'settings:advanced',
                 'destination_id': 'settings',
                 'section_id': 'advanced',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'settings:repair',
                 'destination_id': 'settings',
                 'section_id': 'repair',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'settings:about',
                 'destination_id': 'settings',
                 'section_id': 'about',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True}),
 'sections': ({'id': 'appearance',
               'destination_id': 'settings',
               'label': 'Appearance',
               'icon': 'appearance-theme',
               'order': 10,
               'default_route_id': 'settings',
               'description': 'Application theme and presentation settings.'},
              {'id': 'behavior',
               'destination_id': 'settings',
               'label': 'Behavior',
               'icon': 'settings',
               'order': 20,
               'default_route_id': 'settings:behavior',
               'description': 'Application behavior and navigation preferences.'},
              {'id': 'advanced',
               'destination_id': 'settings',
               'label': 'Specialist Tools',
               'icon': 'developer-tools',
               'order': 30,
               'default_route_id': 'settings:advanced',
               'description': 'Advanced application settings.'},
              {'id': 'repair',
               'destination_id': 'settings',
               'label': 'Repair Loofi',
               'icon': 'maintenance-health',
               'order': 40,
               'default_route_id': 'settings:repair',
               'description': 'Repair application configuration and state.'},
              {'id': 'about',
               'destination_id': 'settings',
               'label': 'About',
               'icon': 'info',
               'order': 50,
               'default_route_id': 'settings:about',
               'description': 'Version, support, and project information.'}),
 'destination': {'id': 'settings',
                 'label': 'Settings',
                 'icon': 'settings',
                 'default_route_id': 'settings',
                 'route_ids': ('settings', 'settings:appearance', 'settings:behavior', 'settings:advanced', 'settings:repair', 'settings:about'),
                 'advanced_only': False}}
