# flake8: noqa
"""Destination-owned product catalog records for software_updates."""

from __future__ import annotations

from typing import Any, Final

RECORDS: Final[dict[str, Any]] = {'plugins': ({'id': 'software',
              'name': 'Software',
              'description': 'Application installer and repository management for Fedora packages.',
              'icon': 'packages-software',
              'destination_id': 'software_updates',
              'module': 'ui.software_tab',
              'class_name': 'SoftwareTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'Packages',
              'badge': 'recommended',
              'order': 10},
             {'id': 'maintenance',
              'name': 'Maintenance',
              'description': 'System updates, cache cleanup, and overlay management for Fedora.',
              'icon': 'maintenance-health',
              'destination_id': 'software_updates',
              'module': 'ui.maintenance_tab',
              'class_name': 'MaintenanceTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'Packages',
              'badge': 'recommended',
              'order': 20}),
 'routes': ({'id': 'software',
             'label': 'Software',
             'plugin_id': 'software',
             'category': 'Packages',
             'icon': 'packages-software',
             'description': 'Applications, repositories, Flatpak, and package sources.',
             'aliases': ('Software', 'Packages'),
             'keywords': ('apps', 'repos', 'flatpak', 'packages'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},
            {'id': 'software:apps',
             'label': 'Applications',
             'plugin_id': 'software',
             'category': 'Packages',
             'icon': 'install',
             'description': 'Install and review application packages.',
             'aliases': ('Apps', 'Applications', 'Install Apps', 'Multimedia Codecs'),
             'keywords': ('apps', 'install', 'software', 'codecs'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'applications'},
            {'id': 'software:repos',
             'label': 'Repositories',
             'plugin_id': 'software',
             'category': 'Packages',
             'icon': 'packages-software',
             'description': 'RPM Fusion, Flathub, COPR, and package repositories.',
             'aliases': ('Repos', 'Repositories', 'RPM Fusion', 'Flathub', 'COPR Repos'),
             'keywords': ('repo', 'repository', 'rpmfusion', 'copr', 'flathub'),
             'risk': 'medium',
             'visibility': 'all',
             'subroute': 'repositories'},
            {'id': 'software:flatpak',
             'label': 'Flatpak Manager',
             'plugin_id': 'software',
             'category': 'Packages',
             'icon': 'packages-software',
             'description': 'Flatpak application and remote management.',
             'aliases': ('Flatpak Manager', 'Flatpak'),
             'keywords': ('flatpak', 'flathub', 'remote'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'flatpak'},
            {'id': 'maintenance',
             'label': 'Maintenance',
             'plugin_id': 'maintenance',
             'category': 'Packages',
             'icon': 'maintenance-health',
             'description': 'System updates, cache cleanup, and overlays.',
             'aliases': ('Maintenance',),
             'keywords': ('update', 'cleanup', 'overlays'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},
            {'id': 'maintenance:updates',
             'label': 'Updates',
             'plugin_id': 'maintenance',
             'category': 'Packages',
             'icon': 'update',
             'description': 'System, Flatpak, and firmware update actions.',
             'aliases': ('Updates', 'Update System', 'Update Flatpaks', 'Firmware Update', 'update_all'),
             'keywords': ('dnf', 'rpm-ostree', 'flatpak', 'firmware'),
             'risk': 'medium',
             'visibility': 'all',
             'subroute': 'updates'},
            {'id': 'maintenance:cleanup',
             'label': 'Cleanup',
             'plugin_id': 'maintenance',
             'category': 'Packages',
             'icon': 'cleanup',
             'description': 'Cache, journal, trim, autoremove, and RPM database cleanup.',
             'aliases': ('Cleanup',
                         'Clean DNF Cache',
                         'Vacuum Journal',
                         'Vacuum Journals',
                         'SSD Trim',
                         'Trim SSD',
                         'Remove Unused Packages',
                         'Rebuild RPM DB',
                         'clean_cache'),
             'keywords': ('clean', 'cache', 'journal', 'trim', 'autoremove', 'rpmdb'),
             'risk': 'medium',
             'visibility': 'all',
             'subroute': 'cleanup'},
            {'id': 'maintenance:smart-updates',
             'label': 'Advanced Update Options',
             'plugin_id': 'maintenance',
             'category': 'Packages',
             'icon': 'update',
             'description': 'Compatibility route to scheduling, conflict preview, and rollback options inside Updates.',
             'aliases': ('Smart Updates',),
             'keywords': ('smart', 'updates', 'plan', 'schedule', 'rollback'),
             'risk': 'medium',
             'visibility': 'all',
             'subroute': 'smart-updates'},
            {'id': 'maintenance:upgrade-assistant',
             'label': 'Upgrade Assistant',
             'plugin_id': 'maintenance',
             'category': 'Packages',
             'icon': 'update',
             'description': 'Guided Fedora release planning, readiness checks, action review, and support export.',
             'aliases': ('Upgrade Assistant', 'Release Upgrade', 'Waypoint', 'Harbor'),
             'keywords': ('upgrade', 'release', 'readiness', 'fedora45', 'waypoint', 'harbor', 'action-center'),
             'risk': 'medium',
             'visibility': 'all',
             'subroute': 'upgrade-assistant'},
            {'id': 'maintenance:action-center',
             'label': 'Action Center',
             'plugin_id': 'maintenance',
             'category': 'Packages',
             'icon': 'maintenance-health',
             'description': 'Preview, queue, confirm, verify, and review recent maintenance actions.',
             'aliases': ('Action Center', 'Action Inbox', 'Harbor Actions'),
             'keywords': ('action', 'preview', 'queue', 'rollback', 'maintenance', 'harbor'),
             'risk': 'medium',
             'visibility': 'all',
             'subroute': 'action-center'},
            {'id': 'maintenance:overlays',
             'label': 'Overlays',
             'plugin_id': 'maintenance',
             'category': 'Packages',
             'icon': 'packages-software',
             'description': 'Atomic Fedora overlay package management.',
             'aliases': ('Overlays',),
             'keywords': ('atomic', 'rpm-ostree', 'layered'),
             'risk': 'high',
             'visibility': 'advanced',
             'subroute': 'overlays'}),
 'placements': ({'route_id': 'software',
                 'destination_id': 'software_updates',
                 'section_id': 'applications',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'software:apps',
                 'destination_id': 'software_updates',
                 'section_id': 'applications',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True,
                 'native_handoff_id': 'plasma.discover'},
                {'route_id': 'software:repos',
                 'destination_id': 'software_updates',
                 'section_id': 'repositories',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'software:flatpak',
                 'destination_id': 'software_updates',
                 'section_id': 'flatpak',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'maintenance',
                 'destination_id': 'software_updates',
                 'section_id': 'updates',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'maintenance:updates',
                 'destination_id': 'software_updates',
                 'section_id': 'updates',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'maintenance:cleanup',
                 'destination_id': 'software_updates',
                 'section_id': 'cleanup',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'maintenance:smart-updates',
                 'destination_id': 'software_updates',
                 'section_id': 'updates',
                 'advanced_only': True,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': 'maintenance:updates',
                 'discoverable': False},
                {'route_id': 'maintenance:upgrade-assistant',
                 'destination_id': 'software_updates',
                 'section_id': 'fedora_upgrade',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'maintenance:action-center',
                 'destination_id': 'software_updates',
                 'section_id': 'maintenance_review',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'maintenance:overlays',
                 'destination_id': 'software_updates',
                 'section_id': 'overlays',
                 'advanced_only': True,
                 'component_id': 'core',
                 'required_capabilities': ('rpm-ostree',),
                 'allowed_variants': ('atomic',),
                 'redirect_route_id': None,
                 'discoverable': True}),
 'sections': ({'id': 'applications',
               'destination_id': 'software_updates',
               'label': 'Applications',
               'icon': 'packages-software',
               'order': 10,
               'default_route_id': 'software:apps',
               'description': 'Find and manage applications.'},
              {'id': 'repositories',
               'destination_id': 'software_updates',
               'label': 'Repositories',
               'icon': 'packages-software',
               'order': 20,
               'default_route_id': 'software:repos',
               'description': 'Manage Fedora software sources.'},
              {'id': 'flatpak',
               'destination_id': 'software_updates',
               'label': 'Flatpak',
               'icon': 'packages-software',
               'order': 30,
               'default_route_id': 'software:flatpak',
               'description': 'Manage Flatpak applications and remotes.'},
              {'id': 'updates',
               'destination_id': 'software_updates',
               'label': 'Updates',
               'icon': 'update',
               'order': 40,
               'default_route_id': 'maintenance',
               'description': 'Review available system updates.'},
              {'id': 'cleanup',
               'destination_id': 'software_updates',
               'label': 'Cleanup',
               'icon': 'cleanup',
               'order': 50,
               'default_route_id': 'maintenance:cleanup',
               'description': 'Analyze reclaimable package and cache data.'},
              {'id': 'fedora_upgrade',
               'destination_id': 'software_updates',
               'label': 'Fedora Upgrade',
               'icon': 'update',
               'order': 60,
               'default_route_id': 'maintenance:upgrade-assistant',
               'description': 'Review Fedora release-upgrade readiness.'},
              {'id': 'maintenance_review',
               'destination_id': 'software_updates',
               'label': 'Action Center',
               'icon': 'maintenance-health',
               'order': 70,
               'default_route_id': 'maintenance:action-center',
               'description': 'Review, plan, run, and verify maintenance actions.'},
              {'id': 'overlays',
               'destination_id': 'software_updates',
               'label': 'Atomic Overlays',
               'icon': 'packages-software',
               'order': 80,
               'default_route_id': 'maintenance:overlays',
               'description': 'Review rpm-ostree layered packages.'}),
 'destination': {'id': 'software_updates',
                 'label': 'Software & Updates',
                 'icon': 'packages-software',
                 'default_route_id': 'software:apps',
                 'route_ids': ('software',
                               'software:apps',
                               'software:repos',
                               'software:flatpak',
                               'maintenance',
                               'maintenance:updates',
                               'maintenance:cleanup',
                               'maintenance:smart-updates',
                               'maintenance:upgrade-assistant',
                               'maintenance:action-center',
                               'maintenance:overlays'),
                 'advanced_only': False}}
