# flake8: noqa
"""Destination-owned product catalog records for system."""

from __future__ import annotations

from typing import Any, Final

RECORDS: Final[dict[str, Any]] = {'plugins': ({'id': 'system_info',
              'name': 'System Info',
              'description': 'Detailed system information including hardware specs, kernel, and uptime.',
              'icon': 'info',
              'destination_id': 'system',
              'module': 'ui.system_info_tab',
              'class_name': 'SystemInfoTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'System',
              'badge': 'recommended',
              'order': 20},
             {'id': 'monitor',
              'name': 'System Monitor',
              'description': 'Live CPU, memory, and process monitoring with performance graphs.',
              'icon': 'overview-dashboard',
              'destination_id': 'system',
              'module': 'ui.monitor_tab',
              'class_name': 'MonitorTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'System',
              'badge': 'recommended',
              'order': 30},
             {'id': 'health',
              'name': 'System Check',
              'description': 'Current findings, saved check history, and supporting health metrics.',
              'icon': 'maintenance-health',
              'destination_id': 'system',
              'module': 'ui.system_check_tab',
              'class_name': 'SystemCheckTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'Maintenance',
              'badge': '',
              'order': 10},
             {'id': 'hardware',
              'name': 'Hardware',
              'description': 'Hardware info and settings including CPU governor, GPU mode, fan control, and battery.',
              'icon': 'hardware-performance',
              'destination_id': 'system',
              'module': 'ui.hardware_tab',
              'class_name': 'HardwareTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'Hardware',
              'badge': 'recommended',
              'order': 10},
             {'id': 'storage',
              'name': 'Storage',
              'description': 'Disk information, SMART health monitoring, and filesystem management.',
              'icon': 'storage-disk',
              'destination_id': 'system',
              'module': 'ui.storage_tab',
              'class_name': 'StorageTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'Hardware',
              'badge': '',
              'order': 40},
             {'id': 'snapshots',
              'name': 'Snapshots',
              'description': 'Unified snapshot management across Timeshift, Snapper, and Btrfs backends.',
              'icon': 'storage-disk',
              'destination_id': 'system',
              'module': 'ui.snapshot_tab',
              'class_name': 'SnapshotTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'Packages',
              'badge': 'advanced',
              'order': 30},
             {'id': 'diagnostics',
              'name': 'Diagnostics',
              'description': 'System diagnostics including service health, boot analysis, and journal review.',
              'icon': 'maintenance-health',
              'destination_id': 'system',
              'module': 'ui.diagnostics_tab',
              'class_name': 'DiagnosticsTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'Maintenance',
              'badge': '',
              'order': 30},
             {'id': 'activity',
              'name': 'Activity & Recovery',
              'description': 'Review trusted local change history and prepare supported recovery.',
              'icon': 'logs',
              'destination_id': 'system',
              'module': 'ui.activity_recovery_tab',
              'class_name': 'ActivityRecoveryTab',
              'component': 'core',
              'visibility': 'standard',
              'compat': {},
              'category': 'System',
              'badge': 'recommended',
              'order': 65}),
 'routes': ({'id': 'dashboard',
             'label': 'System Overview',
             'plugin_id': 'system_info',
             'category': 'System',
             'icon': 'overview-dashboard',
             'description': 'Compatibility route to the maintained System overview.',
             'aliases': ('dashboard', 'system-overview', 'live overview'),
             'keywords': ('overview', 'system information'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},
            {'id': 'system_info',
             'label': 'System Info',
             'plugin_id': 'system_info',
             'category': 'System',
             'icon': 'info',
             'description': 'Hardware, OS, kernel, and release details.',
             'aliases': ('System Info', 'system-info', 'os-details'),
             'keywords': ('fedora', 'kernel', 'hardware', 'specs'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},
            {'id': 'monitor',
             'label': 'Performance & Processes',
             'plugin_id': 'monitor',
             'category': 'System',
             'icon': 'overview-dashboard',
             'description': 'Slow-system guidance, performance graphs, and process management.',
             'aliases': ('System Monitor', 'Performance Monitor'),
             'keywords': ('cpu', 'memory', 'process', 'traffic', 'slow system'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},
            {'id': 'system-monitor:performance',
             'label': 'Performance',
             'plugin_id': 'monitor',
             'category': 'System',
             'icon': 'cpu-performance',
             'description': 'CPU, memory, disk, and network activity.',
             'aliases': ('monitor:performance', 'Performance', 'CPU Usage', 'Memory', 'Disk I/O', 'Network Traffic'),
             'keywords': ('cpu', 'ram', 'memory', 'disk', 'network'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'performance'},
            {'id': 'system-monitor:processes',
             'label': 'Processes',
             'plugin_id': 'monitor',
             'category': 'System',
             'icon': 'terminal-console',
             'description': 'Running process list and process actions.',
             'aliases': ('monitor:processes', 'Processes', 'Kill Process'),
             'keywords': ('process', 'pid', 'top', 'htop', 'kill'),
             'risk': 'medium',
             'visibility': 'all',
             'subroute': 'processes'},
            {'id': 'maintenance:health-timeline',
             'label': 'System Check History',
             'plugin_id': 'health',
             'category': 'Maintenance',
             'icon': 'maintenance-health',
             'description': 'Compatibility route to saved System Check and health history.',
             'aliases': ('Health Timeline', 'My Fedora Today', 'Lighthouse'),
             'keywords': ('health', 'timeline', 'snapshot', 'recurring', 'lighthouse', 'system check'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'history'},
            {'id': 'snapshots',
             'label': 'Recovery Points',
             'plugin_id': 'snapshots',
             'category': 'Packages',
             'icon': 'logs',
             'description': 'Create, list, and restore system recovery points.',
             'aliases': ('Snapshots', 'Create Snapshot', 'Recovery Points'),
             'keywords': ('snapshot', 'timeshift', 'snapper', 'btrfs', 'rollback'),
             'risk': 'medium',
             'visibility': 'advanced',
             'subroute': ''},
            {'id': 'hardware',
             'label': 'Hardware',
             'plugin_id': 'hardware',
             'category': 'Hardware',
             'icon': 'hardware-performance',
             'description': 'Hardware tuning, power, battery, and sensors.',
             'aliases': ('Hardware',
                         'HP Tweaks',
                         'Power Profile',
                         'Power Profile Manager',
                         'Fan Control',
                         'Battery Limit',
                         'Audio Restart',
                         'Fingerprint',
                         'power_profile'),
             'keywords': ('hp', 'battery', 'fan', 'power', 'audio', 'fingerprint'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},
            {'id': 'storage',
             'label': 'Storage',
             'plugin_id': 'storage',
             'category': 'Hardware',
             'icon': 'storage-disk',
             'description': 'Disk, mount, SMART, and usage diagnostics.',
             'aliases': ('Storage', 'Show Disk Usage'),
             'keywords': ('disk', 'mount', 'smart', 'usage'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},
            {'id': 'health',
             'label': 'System Check',
             'plugin_id': 'health',
             'category': 'Maintenance',
             'icon': 'maintenance-health',
             'description': 'Current findings, saved check history, and supporting health metrics.',
             'aliases': ('Health', 'System Health'),
             'keywords': ('health', 'check', 'findings', 'timeline', 'history'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},
            {'id': 'logs',
             'label': 'System Logs',
             'plugin_id': 'logs',
             'category': 'Maintenance',
             'icon': 'logs',
             'description': 'Compatibility route to journal and error review in Troubleshooting.',
             'aliases': ('Logs', 'Smart Logs'),
             'keywords': ('journal', 'logs', 'errors'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': ''},
            {'id': 'diagnostics',
             'label': 'Troubleshooting',
             'plugin_id': 'diagnostics',
             'category': 'Maintenance',
             'icon': 'maintenance-health',
             'description': 'Health, failed services, journal review, and boot diagnostics.',
             'aliases': ('Diagnostics', 'Watchtower', 'Health', 'Logs'),
             'keywords': ('diagnostics', 'boot', 'watchtower', 'journal', 'services'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''},
            {'id': 'diagnostics:watchtower',
             'label': 'Health & Troubleshooting',
             'plugin_id': 'diagnostics',
             'category': 'Maintenance',
             'icon': 'maintenance-health',
             'description': 'System health, service, journal, and support evidence.',
             'aliases': ('Watchtower', 'System Health'),
             'keywords': ('diagnostic', 'doctor', 'health', 'logs'),
             'risk': 'none',
             'visibility': 'all',
             'subroute': 'watchtower'},
            {'id': 'diagnostics:boot',
             'label': 'Boot',
             'plugin_id': 'diagnostics',
             'category': 'Maintenance',
             'icon': 'restart',
             'description': 'Boot time analysis and kernel parameter review.',
             'aliases': ('Boot', 'Boot Analysis', 'Kernel Params'),
             'keywords': ('boot', 'startup', 'kernel', 'grub'),
             'risk': 'none',
             'visibility': 'advanced',
             'subroute': 'boot'},
            {'id': 'activity',
             'label': 'Activity & Recovery',
             'plugin_id': 'activity',
             'category': 'System',
             'icon': 'logs',
             'description': 'Trusted local change history with conservative recovery guidance.',
             'aliases': ('Change Journal', 'Activity', 'Recovery'),
             'keywords': ('changes', 'history', 'dnf5', 'rpm-ostree', 'flatpak', 'firmware', 'recovery'),
             'risk': 'none',
             'visibility': 'beginner',
             'subroute': ''}),
 'placements': ({'route_id': 'dashboard',
                 'destination_id': 'system',
                 'section_id': 'overview',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': 'system_info',
                 'discoverable': False},
                {'route_id': 'system_info',
                 'destination_id': 'system',
                 'section_id': 'overview',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'monitor',
                 'destination_id': 'system',
                 'section_id': 'performance',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'system-monitor:performance',
                 'destination_id': 'system',
                 'section_id': 'performance',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'system-monitor:processes',
                 'destination_id': 'system',
                 'section_id': 'processes',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'maintenance:health-timeline',
                 'destination_id': 'system',
                 'section_id': 'system_check',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'snapshots',
                 'destination_id': 'system',
                 'section_id': 'recovery_points',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'hardware',
                 'destination_id': 'system',
                 'section_id': 'hardware_power',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'storage',
                 'destination_id': 'system',
                 'section_id': 'storage',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'health',
                 'destination_id': 'system',
                 'section_id': 'system_check',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'logs',
                 'destination_id': 'system',
                 'section_id': 'troubleshooting',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': 'diagnostics:watchtower',
                 'discoverable': False},
                {'route_id': 'diagnostics',
                 'destination_id': 'system',
                 'section_id': 'troubleshooting',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'diagnostics:watchtower',
                 'destination_id': 'system',
                 'section_id': 'troubleshooting',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'diagnostics:boot',
                 'destination_id': 'system',
                 'section_id': 'boot_diagnostics',
                 'advanced_only': True,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True},
                {'route_id': 'activity',
                 'destination_id': 'system',
                 'section_id': 'activity_recovery',
                 'advanced_only': False,
                 'component_id': 'core',
                 'required_capabilities': (),
                 'allowed_variants': ('traditional', 'atomic'),
                 'redirect_route_id': None,
                 'discoverable': True}),
 'sections': ({'id': 'overview',
               'destination_id': 'system',
               'label': 'System Information',
               'icon': 'info',
               'order': 10,
               'default_route_id': 'system_info',
               'description': 'Operating system, hardware, and current-state details.'},
              {'id': 'performance',
               'destination_id': 'system',
               'label': 'Performance',
               'icon': 'cpu-performance',
               'order': 20,
               'default_route_id': 'monitor',
               'description': 'Current resource use and performance diagnostics.'},
              {'id': 'processes',
               'destination_id': 'system',
               'label': 'Processes',
               'icon': 'cpu-performance',
               'order': 30,
               'default_route_id': 'system-monitor:processes',
               'description': 'Inspect running processes.'},
              {'id': 'hardware_power',
               'destination_id': 'system',
               'label': 'Hardware & Power',
               'icon': 'hardware-performance',
               'order': 40,
               'default_route_id': 'hardware',
               'description': 'Hardware devices, batteries, and power state.'},
              {'id': 'storage',
               'destination_id': 'system',
               'label': 'Storage',
               'icon': 'storage-disk',
               'order': 50,
               'default_route_id': 'storage',
               'description': 'Disk use and storage health.'},
              {'id': 'system_check',
               'destination_id': 'system',
               'label': 'System Check',
               'icon': 'maintenance-health',
               'order': 60,
               'default_route_id': 'health',
               'description': 'Review current findings, saved checks, and supporting metrics.'},
              {'id': 'troubleshooting',
               'destination_id': 'system',
               'label': 'Troubleshooting',
               'icon': 'maintenance-health',
               'order': 70,
               'default_route_id': 'diagnostics',
               'description': 'Diagnose system issues and inspect evidence.'},
              {'id': 'boot_diagnostics',
               'destination_id': 'system',
               'label': 'Boot Diagnostics',
               'icon': 'logs',
               'order': 80,
               'default_route_id': 'diagnostics:boot',
               'description': 'Inspect boot-time diagnostics.'},
              {'id': 'recovery_points',
               'destination_id': 'system',
               'label': 'Recovery Points',
               'icon': 'storage-disk',
               'order': 90,
               'default_route_id': 'snapshots',
               'description': 'Create and manage recovery points.'},
              {'id': 'activity_recovery',
               'destination_id': 'system',
               'label': 'Activity & Recovery',
               'icon': 'logs',
               'order': 65,
               'default_route_id': 'activity',
               'description': 'Review trusted changes and prepare supported recovery.'}),
 'destination': {'id': 'system',
                 'label': 'System',
                 'icon': 'hardware-performance',
                 'default_route_id': 'system_info',
                 'route_ids': ('dashboard',
                               'system_info',
                               'monitor',
                               'system-monitor:performance',
                               'system-monitor:processes',
                               'hardware',
                               'storage',
                               'health',
                               'maintenance:health-timeline',
                               'diagnostics',
                               'diagnostics:watchtower',
                               'diagnostics:boot',
                               'snapshots',
                               'logs',
                               'activity'),
                 'advanced_only': False}}
