#!/usr/bin/env python3
"""Generate docs/TWEAKS.md from the declarative tweak catalog.

Usage:
    python scripts/gen_tweaks_doc.py          # rewrite docs/TWEAKS.md
    python scripts/gen_tweaks_doc.py --check  # exit 1 if the file is stale
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "loofi-fedora-tweaks"))

from core.tasks.tweaks import TWEAKS, default_for  # noqa: E402

TARGET = ROOT / "docs" / "TWEAKS.md"
DESKTOP = {"gnome": "GNOME", "kde": "KDE Plasma", "all": "All"}


def render() -> str:
    lines = [
        "# Tweak catalog",
        "",
        "> Generated by `scripts/gen_tweaks_doc.py` from `core/tasks/tweaks.py`. Do not edit by hand.",
        "",
        f"Loofi Fedora Tweaks ships **{len(TWEAKS)}** declarative controls. Every change is checked before and after it runs, "
        "and the latest verified change can be restored. Controls marked *needs authorization* ask for administrator approval.",
        "",
    ]
    groups: dict[str, list] = {}
    for tweak in TWEAKS:
        groups.setdefault(tweak.group, []).append(tweak)
    for group in sorted(groups):
        lines += [f"## {group}", "", "| Setting | Desktop | Choices | Default | Notes |", "| --- | --- | --- | --- | --- |"]
        for tweak in sorted(groups[group], key=lambda item: (item.desktop, item.title)):
            labels = {value: label for value, label in tweak.choices}
            choices = ", ".join(label for _value, label in tweak.choices) or "Read from system"
            default = default_for(tweak)
            default_text = labels.get(default, default) or "—"
            notes = "; ".join(part for part in ("needs authorization" if tweak.privileged else "", tweak.effect_hint) if part)
            lines.append(f"| {tweak.title} (`{tweak.id}`) | {DESKTOP.get(tweak.desktop, tweak.desktop)} | {choices} | {default_text} | {notes} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    content = render()
    if "--check" in argv:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != content:
            print("docs/TWEAKS.md is stale; run python scripts/gen_tweaks_doc.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(content, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)} ({len(TWEAKS)} tweaks)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
